import {
  createRootRouteWithContext,
  HeadContent,
  Link,
  Outlet,
  Scripts,
  useRouter,
} from "@tanstack/react-router";
import type { QueryClient } from "@tanstack/react-query";
import { useCallback, type ReactNode } from "react";

import appCss from "../styles.css?url";
import { API_BASE_URL } from "../config/env";
import { AppProviders } from "../app/providers";
import { useHistoryRestoreSync } from "../lib/history-restore";
import { Header } from "../components/layout/Header";
import { Footer } from "../components/layout/Footer";
import { BreadcrumbNav } from "../components/navigation/BreadcrumbNav";

function NotFoundComponent() {
  return (
    <div className="flex min-h-screen flex-col">
      <Header />
      <main className="mx-auto flex w-full max-w-7xl flex-1 flex-col items-start justify-center px-4 py-24 sm:px-6">
        <p className="eyebrow">NASB · Error</p>
        <div className="mt-4 flex items-baseline gap-5">
          <span className="font-serif text-8xl font-bold leading-none text-ink">404</span>
          <span className="gold-rule w-16" aria-hidden="true" />
        </div>
        <h1 className="display-heading mt-4 font-serif text-4xl font-bold text-ink sm:text-5xl">
          This page has moved on.
        </h1>
        <p className="mt-4 max-w-lg text-lg text-muted-text">
          The page you're looking for doesn't exist or has been moved. Let's guide you back to the
          collection.
        </p>
        <Link
          to="/"
          className="mt-8 inline-flex h-12 items-center justify-center rounded-[2px] bg-ink px-8 text-sm font-semibold tracking-wide text-white transition-colors duration-300 hover:bg-dark-gold"
        >
          Back to NASB
        </Link>
      </main>
      <Footer />
    </div>
  );
}

function ErrorComponent({ error, reset }: { error: Error; reset: () => void }) {
  void error;
  const router = useRouter();

  return (
    <div className="flex min-h-screen flex-col">
      <Header />
      <main className="mx-auto flex w-full max-w-7xl flex-1 flex-col items-start justify-center px-4 py-24 sm:px-6">
        <p className="eyebrow">NASB · Error</p>
        <h1 className="display-heading mt-4 font-serif text-4xl font-bold text-ink sm:text-5xl">
          Something went wrong.
        </h1>
        <p className="mt-4 max-w-lg text-lg text-muted-text">
          We couldn't load this page. Please try again — craftsmanship takes patience.
        </p>
        <button
          onClick={() => {
            void router.invalidate();
            reset();
          }}
          className="mt-8 inline-flex h-12 items-center justify-center rounded-[2px] bg-ink px-8 text-sm font-semibold tracking-wide text-white transition-colors duration-300 hover:bg-dark-gold"
        >
          Try again
        </button>
      </main>
      <Footer />
    </div>
  );
}

export const Route = createRootRouteWithContext<{
  queryClient: QueryClient;
}>()({
  head: () => ({
    meta: [
      { charSet: "utf-8" },
      { name: "viewport", content: "width=device-width, initial-scale=1" },
      { title: "NASB — Quality Without Compromise" },
      {
        name: "description",
        content:
          "NASB, made in Nepal by Neupane Aakosh Samik Brothers Pvt. Ltd. Quality without compromise — explore the crafted collection.",
      },
      { property: "og:type", content: "website" },
      { property: "og:site_name", content: "NASB" },
      // Default card for routes without their own OG image.
      { name: "twitter:card", content: "summary" },
    ],
    links: [
      { rel: "stylesheet", href: appCss },
      // NASB brand typefaces: Playfair Display (display serif) + Manrope (sans).
      {
        rel: "preconnect",
        href: "https://fonts.googleapis.com",
      },
      {
        rel: "preconnect",
        href: "https://fonts.gstatic.com",
        crossOrigin: "anonymous",
      },
      {
        rel: "stylesheet",
        href: "https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700&family=Playfair+Display:ital,wght@0,400;0,500;0,600;0,700;0,800;1,400;1,500&display=swap",
      },
      // Sitemap/robots are generated by the backend from real public records
      // (§18); discovery is advertised here. Serving them on the storefront
      // origin itself is a deployment-level reverse-proxy concern.
      { rel: "sitemap", href: `${API_BASE_URL}/public/sitemap.xml` },
      // Preconnect to the API/media origin — required during initial render.
      { rel: "preconnect", href: new URL(API_BASE_URL).origin },
    ],
  }),

  shellComponent: RootShell,
  component: RootComponent,
  notFoundComponent: NotFoundComponent,
  errorComponent: ErrorComponent,
});

function RootShell({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <HeadContent />
      </head>
      <body>
        {children}
        <Scripts />
      </body>
    </html>
  );
}

function RootComponent() {
  const { queryClient } = Route.useRouteContext();
  const router = useRouter();

  // Pages restored from the browser's back/forward cache resume a frozen React
  // tree under a URL the router never observed (a bfcache restore fires only
  // `pageshow`/`persisted:true`, never `popstate`). Re-apply the restored URL —
  // and refresh the queries frozen with it — so a back navigation can never
  // leave the previously visited route rendered under the new URL.
  // See lib/history-restore.ts for the full contract.
  const resyncRestoredLocation = useCallback(
    (href: string) => {
      void router.navigate({ href, replace: true });
    },
    [router],
  );
  useHistoryRestoreSync(resyncRestoredLocation, queryClient);

  return (
    <AppProviders queryClient={queryClient}>
      <a
        href="#main-content"
        className="sr-only focus:not-sr-only focus:absolute focus:left-4 focus:top-4 focus:z-50 focus:rounded-md focus:bg-primary focus:px-4 focus:py-2 focus:text-primary-foreground"
      >
        Skip to content
      </a>
      <div className="flex min-h-screen flex-col">
        <Header />
        {/* tabIndex={-1} lets the skip-to-content anchor move sequential focus
            onto <main> across browsers/route navigation. */}
        <main id="main-content" tabIndex={-1} className="flex-1">
          <BreadcrumbNav />
          <Outlet />
        </main>
        <Footer />
      </div>
    </AppProviders>
  );
}
